services:
    app:
        build: ./
        ports:
            - 8080:8080
        depends_on:
            - db
    db:
        image: postgres:15.1
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432